//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraderaWebService.SearchService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://api.tradera.com", ConfigurationName="TraderaWebService.SearchService.SearchServiceSoap")]
    public interface SearchServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.tradera.com/Search", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TraderaWebService.SearchService.SearchResponse> SearchAsync(TraderaWebService.SearchService.SearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.tradera.com/SearchAdvanced", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TraderaWebService.SearchService.SearchAdvancedResponse> SearchAdvancedAsync(TraderaWebService.SearchService.SearchAdvancedRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.tradera.com/SearchCategoryCount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TraderaWebService.SearchService.SearchCategoryCountResponse> SearchCategoryCountAsync(TraderaWebService.SearchService.SearchCategoryCountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.tradera.com/SearchByFixedCriteria", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TraderaWebService.SearchService.SearchByFixedCriteriaResponse> SearchByFixedCriteriaAsync(TraderaWebService.SearchService.SearchByFixedCriteriaRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.tradera.com/SearchByZipCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TraderaWebService.SearchService.SearchByZipCodeResponse> SearchByZipCodeAsync(TraderaWebService.SearchService.SearchByZipCodeRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tradera.com")]
    public partial class AuthenticationHeader
    {
        
        private int appIdField;
        
        private string appKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int AppId
        {
            get
            {
                return this.appIdField;
            }
            set
            {
                this.appIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AppKey
        {
            get
            {
                return this.appKeyField;
            }
            set
            {
                this.appKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tradera.com")]
    public partial class SearchByZipCodeRequest
    {
        
        private string zipCodeField;
        
        private int pageNumberField;
        
        private string orderByField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ZipCode
        {
            get
            {
                return this.zipCodeField;
            }
            set
            {
                this.zipCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int PageNumber
        {
            get
            {
                return this.pageNumberField;
            }
            set
            {
                this.pageNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string OrderBy
        {
            get
            {
                return this.orderByField;
            }
            set
            {
                this.orderByField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tradera.com")]
    public partial class SearchByFixedCriteriaRequest
    {
        
        private string nameField;
        
        private int pageNumberField;
        
        private string itemTypeField;
        
        private string orderByField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int PageNumber
        {
            get
            {
                return this.pageNumberField;
            }
            set
            {
                this.pageNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ItemType
        {
            get
            {
                return this.itemTypeField;
            }
            set
            {
                this.itemTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string OrderBy
        {
            get
            {
                return this.orderByField;
            }
            set
            {
                this.orderByField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tradera.com")]
    public partial class SearchCategory
    {
        
        private int idField;
        
        private string nameField;
        
        private int noOfItemsInCategoryField;
        
        private int noOfItemsInCategoryIncludingChildrenField;
        
        private SearchCategory[] childCategoriesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int NoOfItemsInCategory
        {
            get
            {
                return this.noOfItemsInCategoryField;
            }
            set
            {
                this.noOfItemsInCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int NoOfItemsInCategoryIncludingChildren
        {
            get
            {
                return this.noOfItemsInCategoryIncludingChildrenField;
            }
            set
            {
                this.noOfItemsInCategoryIncludingChildrenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ChildCategories", Order=4)]
        public SearchCategory[] ChildCategories
        {
            get
            {
                return this.childCategoriesField;
            }
            set
            {
                this.childCategoriesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tradera.com")]
    public partial class CategoryCountResult
    {
        
        private SearchCategory[] categoriesField;
        
        private Error[] errorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Categories", Order=0)]
        public SearchCategory[] Categories
        {
            get
            {
                return this.categoriesField;
            }
            set
            {
                this.categoriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Errors", Order=1)]
        public Error[] Errors
        {
            get
            {
                return this.errorsField;
            }
            set
            {
                this.errorsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tradera.com")]
    public partial class Error
    {
        
        private string codeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tradera.com")]
    public partial class CategoryCountRequest
    {
        
        private int categoryIdField;
        
        private string aliasField;
        
        private int countyIdField;
        
        private bool searchInDescriptionField;
        
        private string itemConditionField;
        
        private string zipCodeField;
        
        private string searchWordsField;
        
        private int pageNumberField;
        
        private bool onlyItemsWithThumbnailField;
        
        private bool onlyAuctionsWithBuyNowField;
        
        private string modeField;
        
        private System.Nullable<int> priceMinimumField;
        
        private System.Nullable<int> priceMaximumField;
        
        private System.Nullable<int> bidsMinimumField;
        
        private System.Nullable<int> bidsMaximumField;
        
        private string itemStatusField;
        
        private string itemTypeField;
        
        private string sellerTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int CategoryId
        {
            get
            {
                return this.categoryIdField;
            }
            set
            {
                this.categoryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Alias
        {
            get
            {
                return this.aliasField;
            }
            set
            {
                this.aliasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int CountyId
        {
            get
            {
                return this.countyIdField;
            }
            set
            {
                this.countyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool SearchInDescription
        {
            get
            {
                return this.searchInDescriptionField;
            }
            set
            {
                this.searchInDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ItemCondition
        {
            get
            {
                return this.itemConditionField;
            }
            set
            {
                this.itemConditionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ZipCode
        {
            get
            {
                return this.zipCodeField;
            }
            set
            {
                this.zipCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string SearchWords
        {
            get
            {
                return this.searchWordsField;
            }
            set
            {
                this.searchWordsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int PageNumber
        {
            get
            {
                return this.pageNumberField;
            }
            set
            {
                this.pageNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool OnlyItemsWithThumbnail
        {
            get
            {
                return this.onlyItemsWithThumbnailField;
            }
            set
            {
                this.onlyItemsWithThumbnailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool OnlyAuctionsWithBuyNow
        {
            get
            {
                return this.onlyAuctionsWithBuyNowField;
            }
            set
            {
                this.onlyAuctionsWithBuyNowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Mode
        {
            get
            {
                return this.modeField;
            }
            set
            {
                this.modeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<int> PriceMinimum
        {
            get
            {
                return this.priceMinimumField;
            }
            set
            {
                this.priceMinimumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<int> PriceMaximum
        {
            get
            {
                return this.priceMaximumField;
            }
            set
            {
                this.priceMaximumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<int> BidsMinimum
        {
            get
            {
                return this.bidsMinimumField;
            }
            set
            {
                this.bidsMinimumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<int> BidsMaximum
        {
            get
            {
                return this.bidsMaximumField;
            }
            set
            {
                this.bidsMaximumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string ItemStatus
        {
            get
            {
                return this.itemStatusField;
            }
            set
            {
                this.itemStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string ItemType
        {
            get
            {
                return this.itemTypeField;
            }
            set
            {
                this.itemTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string SellerType
        {
            get
            {
                return this.sellerTypeField;
            }
            set
            {
                this.sellerTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tradera.com")]
    public partial class AttributeFilter
    {
        
        private string keyField;
        
        private string[] valuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Values", Order=1)]
        public string[] Values
        {
            get
            {
                return this.valuesField;
            }
            set
            {
                this.valuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tradera.com")]
    public partial class SearchAdvancedRequest
    {
        
        private string searchWordsField;
        
        private int categoryIdField;
        
        private bool searchInDescriptionField;
        
        private string modeField;
        
        private System.Nullable<int> priceMinimumField;
        
        private System.Nullable<int> priceMaximumField;
        
        private System.Nullable<int> bidsMinimumField;
        
        private System.Nullable<int> bidsMaximumField;
        
        private string zipCodeField;
        
        private int countyIdField;
        
        private string aliasField;
        
        private string orderByField;
        
        private string itemStatusField;
        
        private string itemTypeField;
        
        private bool onlyAuctionsWithBuyNowField;
        
        private bool onlyItemsWithThumbnailField;
        
        private int itemsPerPageField;
        
        private int pageNumberField;
        
        private string itemConditionField;
        
        private string sellerTypeField;
        
        private string[] brandsField;
        
        private int[] campaignCodeIdsField;
        
        private AttributeFilter[] attributesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SearchWords
        {
            get
            {
                return this.searchWordsField;
            }
            set
            {
                this.searchWordsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int CategoryId
        {
            get
            {
                return this.categoryIdField;
            }
            set
            {
                this.categoryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool SearchInDescription
        {
            get
            {
                return this.searchInDescriptionField;
            }
            set
            {
                this.searchInDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Mode
        {
            get
            {
                return this.modeField;
            }
            set
            {
                this.modeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<int> PriceMinimum
        {
            get
            {
                return this.priceMinimumField;
            }
            set
            {
                this.priceMinimumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<int> PriceMaximum
        {
            get
            {
                return this.priceMaximumField;
            }
            set
            {
                this.priceMaximumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<int> BidsMinimum
        {
            get
            {
                return this.bidsMinimumField;
            }
            set
            {
                this.bidsMinimumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<int> BidsMaximum
        {
            get
            {
                return this.bidsMaximumField;
            }
            set
            {
                this.bidsMaximumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ZipCode
        {
            get
            {
                return this.zipCodeField;
            }
            set
            {
                this.zipCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int CountyId
        {
            get
            {
                return this.countyIdField;
            }
            set
            {
                this.countyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Alias
        {
            get
            {
                return this.aliasField;
            }
            set
            {
                this.aliasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string OrderBy
        {
            get
            {
                return this.orderByField;
            }
            set
            {
                this.orderByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string ItemStatus
        {
            get
            {
                return this.itemStatusField;
            }
            set
            {
                this.itemStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string ItemType
        {
            get
            {
                return this.itemTypeField;
            }
            set
            {
                this.itemTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public bool OnlyAuctionsWithBuyNow
        {
            get
            {
                return this.onlyAuctionsWithBuyNowField;
            }
            set
            {
                this.onlyAuctionsWithBuyNowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public bool OnlyItemsWithThumbnail
        {
            get
            {
                return this.onlyItemsWithThumbnailField;
            }
            set
            {
                this.onlyItemsWithThumbnailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public int ItemsPerPage
        {
            get
            {
                return this.itemsPerPageField;
            }
            set
            {
                this.itemsPerPageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public int PageNumber
        {
            get
            {
                return this.pageNumberField;
            }
            set
            {
                this.pageNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string ItemCondition
        {
            get
            {
                return this.itemConditionField;
            }
            set
            {
                this.itemConditionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string SellerType
        {
            get
            {
                return this.sellerTypeField;
            }
            set
            {
                this.sellerTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=20)]
        public string[] Brands
        {
            get
            {
                return this.brandsField;
            }
            set
            {
                this.brandsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=21)]
        public int[] CampaignCodeIds
        {
            get
            {
                return this.campaignCodeIdsField;
            }
            set
            {
                this.campaignCodeIdsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Attributes", Order=22)]
        public AttributeFilter[] Attributes
        {
            get
            {
                return this.attributesField;
            }
            set
            {
                this.attributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tradera.com")]
    public partial class ConfigurationHeader
    {
        
        private int sandboxField;
        
        private int maxResultAgeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Sandbox
        {
            get
            {
                return this.sandboxField;
            }
            set
            {
                this.sandboxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int MaxResultAge
        {
            get
            {
                return this.maxResultAgeField;
            }
            set
            {
                this.maxResultAgeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tradera.com")]
    public partial class NumberAttributeValue
    {
        
        private int idField;
        
        private string nameField;
        
        private decimal[] valuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public decimal[] Values
        {
            get
            {
                return this.valuesField;
            }
            set
            {
                this.valuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tradera.com")]
    public partial class TermAttributeValue
    {
        
        private int idField;
        
        private string nameField;
        
        private string[] valuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public string[] Values
        {
            get
            {
                return this.valuesField;
            }
            set
            {
                this.valuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tradera.com")]
    public partial class AttributeValues
    {
        
        private TermAttributeValue[] termAttributeValuesField;
        
        private NumberAttributeValue[] numberAttributeValuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public TermAttributeValue[] TermAttributeValues
        {
            get
            {
                return this.termAttributeValuesField;
            }
            set
            {
                this.termAttributeValuesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public NumberAttributeValue[] NumberAttributeValues
        {
            get
            {
                return this.numberAttributeValuesField;
            }
            set
            {
                this.numberAttributeValuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tradera.com")]
    public partial class ImageLink
    {
        
        private string urlField;
        
        private string formatField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Format
        {
            get
            {
                return this.formatField;
            }
            set
            {
                this.formatField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tradera.com")]
    public partial class SearchItem
    {
        
        private int idField;
        
        private string shortDescriptionField;
        
        private System.Nullable<int> buyItNowPriceField;
        
        private int sellerIdField;
        
        private string sellerAliasField;
        
        private System.Nullable<int> maxBidField;
        
        private string thumbnailLinkField;
        
        private double sellerDsrAverageField;
        
        private System.DateTime endDateField;
        
        private System.Nullable<int> nextBidField;
        
        private bool hasBidsField;
        
        private bool isEndedField;
        
        private string itemTypeField;
        
        private string itemUrlField;
        
        private int categoryIdField;
        
        private int bidCountField;
        
        private ImageLink[] imageLinksField;
        
        private AttributeValues attributeValuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ShortDescription
        {
            get
            {
                return this.shortDescriptionField;
            }
            set
            {
                this.shortDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> BuyItNowPrice
        {
            get
            {
                return this.buyItNowPriceField;
            }
            set
            {
                this.buyItNowPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int SellerId
        {
            get
            {
                return this.sellerIdField;
            }
            set
            {
                this.sellerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SellerAlias
        {
            get
            {
                return this.sellerAliasField;
            }
            set
            {
                this.sellerAliasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<int> MaxBid
        {
            get
            {
                return this.maxBidField;
            }
            set
            {
                this.maxBidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ThumbnailLink
        {
            get
            {
                return this.thumbnailLinkField;
            }
            set
            {
                this.thumbnailLinkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public double SellerDsrAverage
        {
            get
            {
                return this.sellerDsrAverageField;
            }
            set
            {
                this.sellerDsrAverageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime EndDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<int> NextBid
        {
            get
            {
                return this.nextBidField;
            }
            set
            {
                this.nextBidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool HasBids
        {
            get
            {
                return this.hasBidsField;
            }
            set
            {
                this.hasBidsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool IsEnded
        {
            get
            {
                return this.isEndedField;
            }
            set
            {
                this.isEndedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string ItemType
        {
            get
            {
                return this.itemTypeField;
            }
            set
            {
                this.itemTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string ItemUrl
        {
            get
            {
                return this.itemUrlField;
            }
            set
            {
                this.itemUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int CategoryId
        {
            get
            {
                return this.categoryIdField;
            }
            set
            {
                this.categoryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int BidCount
        {
            get
            {
                return this.bidCountField;
            }
            set
            {
                this.bidCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=16)]
        public ImageLink[] ImageLinks
        {
            get
            {
                return this.imageLinksField;
            }
            set
            {
                this.imageLinksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public AttributeValues AttributeValues
        {
            get
            {
                return this.attributeValuesField;
            }
            set
            {
                this.attributeValuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tradera.com")]
    public partial class SearchResult
    {
        
        private int totalNumberOfItemsField;
        
        private int totalNumberOfPagesField;
        
        private SearchItem[] itemsField;
        
        private Error[] errorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int TotalNumberOfItems
        {
            get
            {
                return this.totalNumberOfItemsField;
            }
            set
            {
                this.totalNumberOfItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int TotalNumberOfPages
        {
            get
            {
                return this.totalNumberOfPagesField;
            }
            set
            {
                this.totalNumberOfPagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Items", Order=2)]
        public SearchItem[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Errors", Order=3)]
        public Error[] Errors
        {
            get
            {
                return this.errorsField;
            }
            set
            {
                this.errorsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Search", WrapperNamespace="http://api.tradera.com", IsWrapped=true)]
    public partial class SearchRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.tradera.com")]
        public TraderaWebService.SearchService.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.tradera.com")]
        public TraderaWebService.SearchService.ConfigurationHeader ConfigurationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.tradera.com", Order=0)]
        public string query;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.tradera.com", Order=1)]
        public int categoryId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.tradera.com", Order=2)]
        public int pageNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.tradera.com", Order=3)]
        public string orderBy;
        
        public SearchRequest()
        {
        }
        
        public SearchRequest(TraderaWebService.SearchService.AuthenticationHeader AuthenticationHeader, TraderaWebService.SearchService.ConfigurationHeader ConfigurationHeader, string query, int categoryId, int pageNumber, string orderBy)
        {
            this.AuthenticationHeader = AuthenticationHeader;
            this.ConfigurationHeader = ConfigurationHeader;
            this.query = query;
            this.categoryId = categoryId;
            this.pageNumber = pageNumber;
            this.orderBy = orderBy;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchResponse", WrapperNamespace="http://api.tradera.com", IsWrapped=true)]
    public partial class SearchResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.tradera.com", Order=0)]
        public TraderaWebService.SearchService.SearchResult SearchResult;
        
        public SearchResponse()
        {
        }
        
        public SearchResponse(TraderaWebService.SearchService.SearchResult SearchResult)
        {
            this.SearchResult = SearchResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchAdvanced", WrapperNamespace="http://api.tradera.com", IsWrapped=true)]
    public partial class SearchAdvancedRequest1
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.tradera.com")]
        public TraderaWebService.SearchService.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.tradera.com")]
        public TraderaWebService.SearchService.ConfigurationHeader ConfigurationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.tradera.com", Order=0)]
        public TraderaWebService.SearchService.SearchAdvancedRequest request;
        
        public SearchAdvancedRequest1()
        {
        }
        
        public SearchAdvancedRequest1(TraderaWebService.SearchService.AuthenticationHeader AuthenticationHeader, TraderaWebService.SearchService.ConfigurationHeader ConfigurationHeader, TraderaWebService.SearchService.SearchAdvancedRequest request)
        {
            this.AuthenticationHeader = AuthenticationHeader;
            this.ConfigurationHeader = ConfigurationHeader;
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchAdvancedResponse", WrapperNamespace="http://api.tradera.com", IsWrapped=true)]
    public partial class SearchAdvancedResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.tradera.com", Order=0)]
        public TraderaWebService.SearchService.SearchResult SearchAdvancedResult;
        
        public SearchAdvancedResponse()
        {
        }
        
        public SearchAdvancedResponse(TraderaWebService.SearchService.SearchResult SearchAdvancedResult)
        {
            this.SearchAdvancedResult = SearchAdvancedResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchCategoryCount", WrapperNamespace="http://api.tradera.com", IsWrapped=true)]
    public partial class SearchCategoryCountRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.tradera.com")]
        public TraderaWebService.SearchService.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.tradera.com")]
        public TraderaWebService.SearchService.ConfigurationHeader ConfigurationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.tradera.com", Order=0)]
        public TraderaWebService.SearchService.CategoryCountRequest request;
        
        public SearchCategoryCountRequest()
        {
        }
        
        public SearchCategoryCountRequest(TraderaWebService.SearchService.AuthenticationHeader AuthenticationHeader, TraderaWebService.SearchService.ConfigurationHeader ConfigurationHeader, TraderaWebService.SearchService.CategoryCountRequest request)
        {
            this.AuthenticationHeader = AuthenticationHeader;
            this.ConfigurationHeader = ConfigurationHeader;
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchCategoryCountResponse", WrapperNamespace="http://api.tradera.com", IsWrapped=true)]
    public partial class SearchCategoryCountResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.tradera.com", Order=0)]
        public TraderaWebService.SearchService.CategoryCountResult SearchCategoryCountResult;
        
        public SearchCategoryCountResponse()
        {
        }
        
        public SearchCategoryCountResponse(TraderaWebService.SearchService.CategoryCountResult SearchCategoryCountResult)
        {
            this.SearchCategoryCountResult = SearchCategoryCountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchByFixedCriteria", WrapperNamespace="http://api.tradera.com", IsWrapped=true)]
    public partial class SearchByFixedCriteriaRequest1
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.tradera.com")]
        public TraderaWebService.SearchService.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.tradera.com")]
        public TraderaWebService.SearchService.ConfigurationHeader ConfigurationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.tradera.com", Order=0)]
        public TraderaWebService.SearchService.SearchByFixedCriteriaRequest request;
        
        public SearchByFixedCriteriaRequest1()
        {
        }
        
        public SearchByFixedCriteriaRequest1(TraderaWebService.SearchService.AuthenticationHeader AuthenticationHeader, TraderaWebService.SearchService.ConfigurationHeader ConfigurationHeader, TraderaWebService.SearchService.SearchByFixedCriteriaRequest request)
        {
            this.AuthenticationHeader = AuthenticationHeader;
            this.ConfigurationHeader = ConfigurationHeader;
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchByFixedCriteriaResponse", WrapperNamespace="http://api.tradera.com", IsWrapped=true)]
    public partial class SearchByFixedCriteriaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.tradera.com", Order=0)]
        public TraderaWebService.SearchService.SearchResult SearchByFixedCriteriaResult;
        
        public SearchByFixedCriteriaResponse()
        {
        }
        
        public SearchByFixedCriteriaResponse(TraderaWebService.SearchService.SearchResult SearchByFixedCriteriaResult)
        {
            this.SearchByFixedCriteriaResult = SearchByFixedCriteriaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchByZipCode", WrapperNamespace="http://api.tradera.com", IsWrapped=true)]
    public partial class SearchByZipCodeRequest1
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.tradera.com")]
        public TraderaWebService.SearchService.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.tradera.com")]
        public TraderaWebService.SearchService.ConfigurationHeader ConfigurationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.tradera.com", Order=0)]
        public TraderaWebService.SearchService.SearchByZipCodeRequest request;
        
        public SearchByZipCodeRequest1()
        {
        }
        
        public SearchByZipCodeRequest1(TraderaWebService.SearchService.AuthenticationHeader AuthenticationHeader, TraderaWebService.SearchService.ConfigurationHeader ConfigurationHeader, TraderaWebService.SearchService.SearchByZipCodeRequest request)
        {
            this.AuthenticationHeader = AuthenticationHeader;
            this.ConfigurationHeader = ConfigurationHeader;
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchByZipCodeResponse", WrapperNamespace="http://api.tradera.com", IsWrapped=true)]
    public partial class SearchByZipCodeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.tradera.com", Order=0)]
        public TraderaWebService.SearchService.SearchResult SearchByZipCodeResult;
        
        public SearchByZipCodeResponse()
        {
        }
        
        public SearchByZipCodeResponse(TraderaWebService.SearchService.SearchResult SearchByZipCodeResult)
        {
            this.SearchByZipCodeResult = SearchByZipCodeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface SearchServiceSoapChannel : TraderaWebService.SearchService.SearchServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class SearchServiceSoapClient : System.ServiceModel.ClientBase<TraderaWebService.SearchService.SearchServiceSoap>, TraderaWebService.SearchService.SearchServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SearchServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(SearchServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), SearchServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SearchServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SearchServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SearchServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SearchServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SearchServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TraderaWebService.SearchService.SearchResponse> TraderaWebService.SearchService.SearchServiceSoap.SearchAsync(TraderaWebService.SearchService.SearchRequest request)
        {
            return base.Channel.SearchAsync(request);
        }
        
        public System.Threading.Tasks.Task<TraderaWebService.SearchService.SearchResponse> SearchAsync(TraderaWebService.SearchService.AuthenticationHeader AuthenticationHeader, TraderaWebService.SearchService.ConfigurationHeader ConfigurationHeader, string query, int categoryId, int pageNumber, string orderBy)
        {
            TraderaWebService.SearchService.SearchRequest inValue = new TraderaWebService.SearchService.SearchRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.ConfigurationHeader = ConfigurationHeader;
            inValue.query = query;
            inValue.categoryId = categoryId;
            inValue.pageNumber = pageNumber;
            inValue.orderBy = orderBy;
            return ((TraderaWebService.SearchService.SearchServiceSoap)(this)).SearchAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TraderaWebService.SearchService.SearchAdvancedResponse> TraderaWebService.SearchService.SearchServiceSoap.SearchAdvancedAsync(TraderaWebService.SearchService.SearchAdvancedRequest1 request)
        {
            return base.Channel.SearchAdvancedAsync(request);
        }
        
        public System.Threading.Tasks.Task<TraderaWebService.SearchService.SearchAdvancedResponse> SearchAdvancedAsync(TraderaWebService.SearchService.AuthenticationHeader AuthenticationHeader, TraderaWebService.SearchService.ConfigurationHeader ConfigurationHeader, TraderaWebService.SearchService.SearchAdvancedRequest request)
        {
            TraderaWebService.SearchService.SearchAdvancedRequest1 inValue = new TraderaWebService.SearchService.SearchAdvancedRequest1();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.ConfigurationHeader = ConfigurationHeader;
            inValue.request = request;
            return ((TraderaWebService.SearchService.SearchServiceSoap)(this)).SearchAdvancedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TraderaWebService.SearchService.SearchCategoryCountResponse> TraderaWebService.SearchService.SearchServiceSoap.SearchCategoryCountAsync(TraderaWebService.SearchService.SearchCategoryCountRequest request)
        {
            return base.Channel.SearchCategoryCountAsync(request);
        }
        
        public System.Threading.Tasks.Task<TraderaWebService.SearchService.SearchCategoryCountResponse> SearchCategoryCountAsync(TraderaWebService.SearchService.AuthenticationHeader AuthenticationHeader, TraderaWebService.SearchService.ConfigurationHeader ConfigurationHeader, TraderaWebService.SearchService.CategoryCountRequest request)
        {
            TraderaWebService.SearchService.SearchCategoryCountRequest inValue = new TraderaWebService.SearchService.SearchCategoryCountRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.ConfigurationHeader = ConfigurationHeader;
            inValue.request = request;
            return ((TraderaWebService.SearchService.SearchServiceSoap)(this)).SearchCategoryCountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TraderaWebService.SearchService.SearchByFixedCriteriaResponse> TraderaWebService.SearchService.SearchServiceSoap.SearchByFixedCriteriaAsync(TraderaWebService.SearchService.SearchByFixedCriteriaRequest1 request)
        {
            return base.Channel.SearchByFixedCriteriaAsync(request);
        }
        
        public System.Threading.Tasks.Task<TraderaWebService.SearchService.SearchByFixedCriteriaResponse> SearchByFixedCriteriaAsync(TraderaWebService.SearchService.AuthenticationHeader AuthenticationHeader, TraderaWebService.SearchService.ConfigurationHeader ConfigurationHeader, TraderaWebService.SearchService.SearchByFixedCriteriaRequest request)
        {
            TraderaWebService.SearchService.SearchByFixedCriteriaRequest1 inValue = new TraderaWebService.SearchService.SearchByFixedCriteriaRequest1();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.ConfigurationHeader = ConfigurationHeader;
            inValue.request = request;
            return ((TraderaWebService.SearchService.SearchServiceSoap)(this)).SearchByFixedCriteriaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TraderaWebService.SearchService.SearchByZipCodeResponse> TraderaWebService.SearchService.SearchServiceSoap.SearchByZipCodeAsync(TraderaWebService.SearchService.SearchByZipCodeRequest1 request)
        {
            return base.Channel.SearchByZipCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<TraderaWebService.SearchService.SearchByZipCodeResponse> SearchByZipCodeAsync(TraderaWebService.SearchService.AuthenticationHeader AuthenticationHeader, TraderaWebService.SearchService.ConfigurationHeader ConfigurationHeader, TraderaWebService.SearchService.SearchByZipCodeRequest request)
        {
            TraderaWebService.SearchService.SearchByZipCodeRequest1 inValue = new TraderaWebService.SearchService.SearchByZipCodeRequest1();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.ConfigurationHeader = ConfigurationHeader;
            inValue.request = request;
            return ((TraderaWebService.SearchService.SearchServiceSoap)(this)).SearchByZipCodeAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SearchServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.SearchServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SearchServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://api.tradera.com/v3/searchservice.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.SearchServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://api.tradera.com/v3/searchservice.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            SearchServiceSoap,
            
            SearchServiceSoap12,
        }
    }
}
