//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraderaWebService.SearchService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://api.tradera.com", ConfigurationName="SearchService.SearchServiceSoap")]
    public interface SearchServiceSoap {
        
        // CODEGEN: Generating message contract since message SearchRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://api.tradera.com/Search", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TraderaWebService.SearchService.SearchResponse Search(TraderaWebService.SearchService.SearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://api.tradera.com/Search", ReplyAction="*")]
        System.IAsyncResult BeginSearch(TraderaWebService.SearchService.SearchRequest request, System.AsyncCallback callback, object asyncState);
        
        TraderaWebService.SearchService.SearchResponse EndSearch(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since message SearchAdvancedRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://api.tradera.com/SearchAdvanced", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TraderaWebService.SearchService.SearchAdvancedResponse SearchAdvanced(TraderaWebService.SearchService.SearchAdvancedRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://api.tradera.com/SearchAdvanced", ReplyAction="*")]
        System.IAsyncResult BeginSearchAdvanced(TraderaWebService.SearchService.SearchAdvancedRequest1 request, System.AsyncCallback callback, object asyncState);
        
        TraderaWebService.SearchService.SearchAdvancedResponse EndSearchAdvanced(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since message SearchCategoryCountRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://api.tradera.com/SearchCategoryCount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TraderaWebService.SearchService.SearchCategoryCountResponse SearchCategoryCount(TraderaWebService.SearchService.SearchCategoryCountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://api.tradera.com/SearchCategoryCount", ReplyAction="*")]
        System.IAsyncResult BeginSearchCategoryCount(TraderaWebService.SearchService.SearchCategoryCountRequest request, System.AsyncCallback callback, object asyncState);
        
        TraderaWebService.SearchService.SearchCategoryCountResponse EndSearchCategoryCount(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since message SearchByFixedCriteriaRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://api.tradera.com/SearchByFixedCriteria", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TraderaWebService.SearchService.SearchByFixedCriteriaResponse SearchByFixedCriteria(TraderaWebService.SearchService.SearchByFixedCriteriaRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://api.tradera.com/SearchByFixedCriteria", ReplyAction="*")]
        System.IAsyncResult BeginSearchByFixedCriteria(TraderaWebService.SearchService.SearchByFixedCriteriaRequest1 request, System.AsyncCallback callback, object asyncState);
        
        TraderaWebService.SearchService.SearchByFixedCriteriaResponse EndSearchByFixedCriteria(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since message SearchByZipCodeRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://api.tradera.com/SearchByZipCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TraderaWebService.SearchService.SearchByZipCodeResponse SearchByZipCode(TraderaWebService.SearchService.SearchByZipCodeRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://api.tradera.com/SearchByZipCode", ReplyAction="*")]
        System.IAsyncResult BeginSearchByZipCode(TraderaWebService.SearchService.SearchByZipCodeRequest1 request, System.AsyncCallback callback, object asyncState);
        
        TraderaWebService.SearchService.SearchByZipCodeResponse EndSearchByZipCode(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tradera.com")]
    public partial class AuthenticationHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int appIdField;
        
        private string appKeyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int AppId {
            get {
                return this.appIdField;
            }
            set {
                this.appIdField = value;
                this.RaisePropertyChanged("AppId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AppKey {
            get {
                return this.appKeyField;
            }
            set {
                this.appKeyField = value;
                this.RaisePropertyChanged("AppKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tradera.com")]
    public partial class SearchByZipCodeRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string zipCodeField;
        
        private int pageNumberField;
        
        private string orderByField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ZipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
                this.RaisePropertyChanged("ZipCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int PageNumber {
            get {
                return this.pageNumberField;
            }
            set {
                this.pageNumberField = value;
                this.RaisePropertyChanged("PageNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string OrderBy {
            get {
                return this.orderByField;
            }
            set {
                this.orderByField = value;
                this.RaisePropertyChanged("OrderBy");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tradera.com")]
    public partial class SearchByFixedCriteriaRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private int pageNumberField;
        
        private string itemTypeField;
        
        private string orderByField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int PageNumber {
            get {
                return this.pageNumberField;
            }
            set {
                this.pageNumberField = value;
                this.RaisePropertyChanged("PageNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ItemType {
            get {
                return this.itemTypeField;
            }
            set {
                this.itemTypeField = value;
                this.RaisePropertyChanged("ItemType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string OrderBy {
            get {
                return this.orderByField;
            }
            set {
                this.orderByField = value;
                this.RaisePropertyChanged("OrderBy");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tradera.com")]
    public partial class SearchCategory : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        private int noOfItemsInCategoryField;
        
        private int noOfItemsInCategoryIncludingChildrenField;
        
        private SearchCategory[] childCategoriesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int NoOfItemsInCategory {
            get {
                return this.noOfItemsInCategoryField;
            }
            set {
                this.noOfItemsInCategoryField = value;
                this.RaisePropertyChanged("NoOfItemsInCategory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int NoOfItemsInCategoryIncludingChildren {
            get {
                return this.noOfItemsInCategoryIncludingChildrenField;
            }
            set {
                this.noOfItemsInCategoryIncludingChildrenField = value;
                this.RaisePropertyChanged("NoOfItemsInCategoryIncludingChildren");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ChildCategories", Order=4)]
        public SearchCategory[] ChildCategories {
            get {
                return this.childCategoriesField;
            }
            set {
                this.childCategoriesField = value;
                this.RaisePropertyChanged("ChildCategories");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tradera.com")]
    public partial class CategoryCountResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SearchCategory[] categoriesField;
        
        private Error[] errorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Categories", Order=0)]
        public SearchCategory[] Categories {
            get {
                return this.categoriesField;
            }
            set {
                this.categoriesField = value;
                this.RaisePropertyChanged("Categories");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Errors", Order=1)]
        public Error[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
                this.RaisePropertyChanged("Errors");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tradera.com")]
    public partial class Error : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tradera.com")]
    public partial class CategoryCountRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int categoryIdField;
        
        private string aliasField;
        
        private int countyIdField;
        
        private bool searchInDescriptionField;
        
        private string itemConditionField;
        
        private string zipCodeField;
        
        private string searchWordsField;
        
        private int pageNumberField;
        
        private bool onlyItemsWithThumbnailField;
        
        private bool onlyAuctionsWithBuyNowField;
        
        private string modeField;
        
        private System.Nullable<int> priceMinimumField;
        
        private System.Nullable<int> priceMaximumField;
        
        private System.Nullable<int> bidsMinimumField;
        
        private System.Nullable<int> bidsMaximumField;
        
        private string itemStatusField;
        
        private string itemTypeField;
        
        private string sellerTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int CategoryId {
            get {
                return this.categoryIdField;
            }
            set {
                this.categoryIdField = value;
                this.RaisePropertyChanged("CategoryId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
                this.RaisePropertyChanged("Alias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int CountyId {
            get {
                return this.countyIdField;
            }
            set {
                this.countyIdField = value;
                this.RaisePropertyChanged("CountyId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool SearchInDescription {
            get {
                return this.searchInDescriptionField;
            }
            set {
                this.searchInDescriptionField = value;
                this.RaisePropertyChanged("SearchInDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ItemCondition {
            get {
                return this.itemConditionField;
            }
            set {
                this.itemConditionField = value;
                this.RaisePropertyChanged("ItemCondition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ZipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
                this.RaisePropertyChanged("ZipCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string SearchWords {
            get {
                return this.searchWordsField;
            }
            set {
                this.searchWordsField = value;
                this.RaisePropertyChanged("SearchWords");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int PageNumber {
            get {
                return this.pageNumberField;
            }
            set {
                this.pageNumberField = value;
                this.RaisePropertyChanged("PageNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool OnlyItemsWithThumbnail {
            get {
                return this.onlyItemsWithThumbnailField;
            }
            set {
                this.onlyItemsWithThumbnailField = value;
                this.RaisePropertyChanged("OnlyItemsWithThumbnail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool OnlyAuctionsWithBuyNow {
            get {
                return this.onlyAuctionsWithBuyNowField;
            }
            set {
                this.onlyAuctionsWithBuyNowField = value;
                this.RaisePropertyChanged("OnlyAuctionsWithBuyNow");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
                this.RaisePropertyChanged("Mode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<int> PriceMinimum {
            get {
                return this.priceMinimumField;
            }
            set {
                this.priceMinimumField = value;
                this.RaisePropertyChanged("PriceMinimum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<int> PriceMaximum {
            get {
                return this.priceMaximumField;
            }
            set {
                this.priceMaximumField = value;
                this.RaisePropertyChanged("PriceMaximum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<int> BidsMinimum {
            get {
                return this.bidsMinimumField;
            }
            set {
                this.bidsMinimumField = value;
                this.RaisePropertyChanged("BidsMinimum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<int> BidsMaximum {
            get {
                return this.bidsMaximumField;
            }
            set {
                this.bidsMaximumField = value;
                this.RaisePropertyChanged("BidsMaximum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string ItemStatus {
            get {
                return this.itemStatusField;
            }
            set {
                this.itemStatusField = value;
                this.RaisePropertyChanged("ItemStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string ItemType {
            get {
                return this.itemTypeField;
            }
            set {
                this.itemTypeField = value;
                this.RaisePropertyChanged("ItemType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string SellerType {
            get {
                return this.sellerTypeField;
            }
            set {
                this.sellerTypeField = value;
                this.RaisePropertyChanged("SellerType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tradera.com")]
    public partial class SearchAdvancedRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string searchWordsField;
        
        private int categoryIdField;
        
        private bool searchInDescriptionField;
        
        private string modeField;
        
        private System.Nullable<int> priceMinimumField;
        
        private System.Nullable<int> priceMaximumField;
        
        private System.Nullable<int> bidsMinimumField;
        
        private System.Nullable<int> bidsMaximumField;
        
        private string zipCodeField;
        
        private int countyIdField;
        
        private string aliasField;
        
        private string orderByField;
        
        private string itemStatusField;
        
        private string itemTypeField;
        
        private bool onlyAuctionsWithBuyNowField;
        
        private bool onlyItemsWithThumbnailField;
        
        private int itemsPerPageField;
        
        private int pageNumberField;
        
        private string itemConditionField;
        
        private string sellerTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SearchWords {
            get {
                return this.searchWordsField;
            }
            set {
                this.searchWordsField = value;
                this.RaisePropertyChanged("SearchWords");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int CategoryId {
            get {
                return this.categoryIdField;
            }
            set {
                this.categoryIdField = value;
                this.RaisePropertyChanged("CategoryId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool SearchInDescription {
            get {
                return this.searchInDescriptionField;
            }
            set {
                this.searchInDescriptionField = value;
                this.RaisePropertyChanged("SearchInDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
                this.RaisePropertyChanged("Mode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<int> PriceMinimum {
            get {
                return this.priceMinimumField;
            }
            set {
                this.priceMinimumField = value;
                this.RaisePropertyChanged("PriceMinimum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<int> PriceMaximum {
            get {
                return this.priceMaximumField;
            }
            set {
                this.priceMaximumField = value;
                this.RaisePropertyChanged("PriceMaximum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<int> BidsMinimum {
            get {
                return this.bidsMinimumField;
            }
            set {
                this.bidsMinimumField = value;
                this.RaisePropertyChanged("BidsMinimum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<int> BidsMaximum {
            get {
                return this.bidsMaximumField;
            }
            set {
                this.bidsMaximumField = value;
                this.RaisePropertyChanged("BidsMaximum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ZipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
                this.RaisePropertyChanged("ZipCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int CountyId {
            get {
                return this.countyIdField;
            }
            set {
                this.countyIdField = value;
                this.RaisePropertyChanged("CountyId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
                this.RaisePropertyChanged("Alias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string OrderBy {
            get {
                return this.orderByField;
            }
            set {
                this.orderByField = value;
                this.RaisePropertyChanged("OrderBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string ItemStatus {
            get {
                return this.itemStatusField;
            }
            set {
                this.itemStatusField = value;
                this.RaisePropertyChanged("ItemStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string ItemType {
            get {
                return this.itemTypeField;
            }
            set {
                this.itemTypeField = value;
                this.RaisePropertyChanged("ItemType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public bool OnlyAuctionsWithBuyNow {
            get {
                return this.onlyAuctionsWithBuyNowField;
            }
            set {
                this.onlyAuctionsWithBuyNowField = value;
                this.RaisePropertyChanged("OnlyAuctionsWithBuyNow");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public bool OnlyItemsWithThumbnail {
            get {
                return this.onlyItemsWithThumbnailField;
            }
            set {
                this.onlyItemsWithThumbnailField = value;
                this.RaisePropertyChanged("OnlyItemsWithThumbnail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public int ItemsPerPage {
            get {
                return this.itemsPerPageField;
            }
            set {
                this.itemsPerPageField = value;
                this.RaisePropertyChanged("ItemsPerPage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public int PageNumber {
            get {
                return this.pageNumberField;
            }
            set {
                this.pageNumberField = value;
                this.RaisePropertyChanged("PageNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string ItemCondition {
            get {
                return this.itemConditionField;
            }
            set {
                this.itemConditionField = value;
                this.RaisePropertyChanged("ItemCondition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string SellerType {
            get {
                return this.sellerTypeField;
            }
            set {
                this.sellerTypeField = value;
                this.RaisePropertyChanged("SellerType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tradera.com")]
    public partial class ConfigurationHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int sandboxField;
        
        private int maxResultAgeField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Sandbox {
            get {
                return this.sandboxField;
            }
            set {
                this.sandboxField = value;
                this.RaisePropertyChanged("Sandbox");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int MaxResultAge {
            get {
                return this.maxResultAgeField;
            }
            set {
                this.maxResultAgeField = value;
                this.RaisePropertyChanged("MaxResultAge");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tradera.com")]
    public partial class SearchItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string shortDescriptionField;
        
        private System.Nullable<int> buyItNowPriceField;
        
        private int sellerIdField;
        
        private string sellerAliasField;
        
        private System.Nullable<int> maxBidField;
        
        private string thumbnailLinkField;
        
        private double sellerDsrAverageField;
        
        private System.DateTime endDateField;
        
        private System.Nullable<int> nextBidField;
        
        private bool hasBidsField;
        
        private bool isEndedField;
        
        private string itemTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ShortDescription {
            get {
                return this.shortDescriptionField;
            }
            set {
                this.shortDescriptionField = value;
                this.RaisePropertyChanged("ShortDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> BuyItNowPrice {
            get {
                return this.buyItNowPriceField;
            }
            set {
                this.buyItNowPriceField = value;
                this.RaisePropertyChanged("BuyItNowPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int SellerId {
            get {
                return this.sellerIdField;
            }
            set {
                this.sellerIdField = value;
                this.RaisePropertyChanged("SellerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SellerAlias {
            get {
                return this.sellerAliasField;
            }
            set {
                this.sellerAliasField = value;
                this.RaisePropertyChanged("SellerAlias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<int> MaxBid {
            get {
                return this.maxBidField;
            }
            set {
                this.maxBidField = value;
                this.RaisePropertyChanged("MaxBid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ThumbnailLink {
            get {
                return this.thumbnailLinkField;
            }
            set {
                this.thumbnailLinkField = value;
                this.RaisePropertyChanged("ThumbnailLink");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public double SellerDsrAverage {
            get {
                return this.sellerDsrAverageField;
            }
            set {
                this.sellerDsrAverageField = value;
                this.RaisePropertyChanged("SellerDsrAverage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
                this.RaisePropertyChanged("EndDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<int> NextBid {
            get {
                return this.nextBidField;
            }
            set {
                this.nextBidField = value;
                this.RaisePropertyChanged("NextBid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool HasBids {
            get {
                return this.hasBidsField;
            }
            set {
                this.hasBidsField = value;
                this.RaisePropertyChanged("HasBids");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool IsEnded {
            get {
                return this.isEndedField;
            }
            set {
                this.isEndedField = value;
                this.RaisePropertyChanged("IsEnded");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string ItemType {
            get {
                return this.itemTypeField;
            }
            set {
                this.itemTypeField = value;
                this.RaisePropertyChanged("ItemType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tradera.com")]
    public partial class SearchResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int totalNumberOfItemsField;
        
        private int totalNumberOfPagesField;
        
        private SearchItem[] itemsField;
        
        private Error[] errorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int TotalNumberOfItems {
            get {
                return this.totalNumberOfItemsField;
            }
            set {
                this.totalNumberOfItemsField = value;
                this.RaisePropertyChanged("TotalNumberOfItems");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int TotalNumberOfPages {
            get {
                return this.totalNumberOfPagesField;
            }
            set {
                this.totalNumberOfPagesField = value;
                this.RaisePropertyChanged("TotalNumberOfPages");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Items", Order=2)]
        public SearchItem[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Errors", Order=3)]
        public Error[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
                this.RaisePropertyChanged("Errors");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Search", WrapperNamespace="http://api.tradera.com", IsWrapped=true)]
    public partial class SearchRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.tradera.com")]
        public TraderaWebService.SearchService.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.tradera.com")]
        public TraderaWebService.SearchService.ConfigurationHeader ConfigurationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.tradera.com", Order=0)]
        public string query;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.tradera.com", Order=1)]
        public int categoryId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.tradera.com", Order=2)]
        public int pageNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.tradera.com", Order=3)]
        public string orderBy;
        
        public SearchRequest() {
        }
        
        public SearchRequest(TraderaWebService.SearchService.AuthenticationHeader AuthenticationHeader, TraderaWebService.SearchService.ConfigurationHeader ConfigurationHeader, string query, int categoryId, int pageNumber, string orderBy) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.ConfigurationHeader = ConfigurationHeader;
            this.query = query;
            this.categoryId = categoryId;
            this.pageNumber = pageNumber;
            this.orderBy = orderBy;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchResponse", WrapperNamespace="http://api.tradera.com", IsWrapped=true)]
    public partial class SearchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.tradera.com", Order=0)]
        public TraderaWebService.SearchService.SearchResult SearchResult;
        
        public SearchResponse() {
        }
        
        public SearchResponse(TraderaWebService.SearchService.SearchResult SearchResult) {
            this.SearchResult = SearchResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchAdvanced", WrapperNamespace="http://api.tradera.com", IsWrapped=true)]
    public partial class SearchAdvancedRequest1 {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.tradera.com")]
        public TraderaWebService.SearchService.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.tradera.com")]
        public TraderaWebService.SearchService.ConfigurationHeader ConfigurationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.tradera.com", Order=0)]
        public TraderaWebService.SearchService.SearchAdvancedRequest request;
        
        public SearchAdvancedRequest1() {
        }
        
        public SearchAdvancedRequest1(TraderaWebService.SearchService.AuthenticationHeader AuthenticationHeader, TraderaWebService.SearchService.ConfigurationHeader ConfigurationHeader, TraderaWebService.SearchService.SearchAdvancedRequest request) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.ConfigurationHeader = ConfigurationHeader;
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchAdvancedResponse", WrapperNamespace="http://api.tradera.com", IsWrapped=true)]
    public partial class SearchAdvancedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.tradera.com", Order=0)]
        public TraderaWebService.SearchService.SearchResult SearchAdvancedResult;
        
        public SearchAdvancedResponse() {
        }
        
        public SearchAdvancedResponse(TraderaWebService.SearchService.SearchResult SearchAdvancedResult) {
            this.SearchAdvancedResult = SearchAdvancedResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchCategoryCount", WrapperNamespace="http://api.tradera.com", IsWrapped=true)]
    public partial class SearchCategoryCountRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.tradera.com")]
        public TraderaWebService.SearchService.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.tradera.com")]
        public TraderaWebService.SearchService.ConfigurationHeader ConfigurationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.tradera.com", Order=0)]
        public TraderaWebService.SearchService.CategoryCountRequest request;
        
        public SearchCategoryCountRequest() {
        }
        
        public SearchCategoryCountRequest(TraderaWebService.SearchService.AuthenticationHeader AuthenticationHeader, TraderaWebService.SearchService.ConfigurationHeader ConfigurationHeader, TraderaWebService.SearchService.CategoryCountRequest request) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.ConfigurationHeader = ConfigurationHeader;
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchCategoryCountResponse", WrapperNamespace="http://api.tradera.com", IsWrapped=true)]
    public partial class SearchCategoryCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.tradera.com", Order=0)]
        public TraderaWebService.SearchService.CategoryCountResult SearchCategoryCountResult;
        
        public SearchCategoryCountResponse() {
        }
        
        public SearchCategoryCountResponse(TraderaWebService.SearchService.CategoryCountResult SearchCategoryCountResult) {
            this.SearchCategoryCountResult = SearchCategoryCountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchByFixedCriteria", WrapperNamespace="http://api.tradera.com", IsWrapped=true)]
    public partial class SearchByFixedCriteriaRequest1 {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.tradera.com")]
        public TraderaWebService.SearchService.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.tradera.com")]
        public TraderaWebService.SearchService.ConfigurationHeader ConfigurationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.tradera.com", Order=0)]
        public TraderaWebService.SearchService.SearchByFixedCriteriaRequest request;
        
        public SearchByFixedCriteriaRequest1() {
        }
        
        public SearchByFixedCriteriaRequest1(TraderaWebService.SearchService.AuthenticationHeader AuthenticationHeader, TraderaWebService.SearchService.ConfigurationHeader ConfigurationHeader, TraderaWebService.SearchService.SearchByFixedCriteriaRequest request) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.ConfigurationHeader = ConfigurationHeader;
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchByFixedCriteriaResponse", WrapperNamespace="http://api.tradera.com", IsWrapped=true)]
    public partial class SearchByFixedCriteriaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.tradera.com", Order=0)]
        public TraderaWebService.SearchService.SearchResult SearchByFixedCriteriaResult;
        
        public SearchByFixedCriteriaResponse() {
        }
        
        public SearchByFixedCriteriaResponse(TraderaWebService.SearchService.SearchResult SearchByFixedCriteriaResult) {
            this.SearchByFixedCriteriaResult = SearchByFixedCriteriaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchByZipCode", WrapperNamespace="http://api.tradera.com", IsWrapped=true)]
    public partial class SearchByZipCodeRequest1 {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.tradera.com")]
        public TraderaWebService.SearchService.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.tradera.com")]
        public TraderaWebService.SearchService.ConfigurationHeader ConfigurationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.tradera.com", Order=0)]
        public TraderaWebService.SearchService.SearchByZipCodeRequest request;
        
        public SearchByZipCodeRequest1() {
        }
        
        public SearchByZipCodeRequest1(TraderaWebService.SearchService.AuthenticationHeader AuthenticationHeader, TraderaWebService.SearchService.ConfigurationHeader ConfigurationHeader, TraderaWebService.SearchService.SearchByZipCodeRequest request) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.ConfigurationHeader = ConfigurationHeader;
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchByZipCodeResponse", WrapperNamespace="http://api.tradera.com", IsWrapped=true)]
    public partial class SearchByZipCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.tradera.com", Order=0)]
        public TraderaWebService.SearchService.SearchResult SearchByZipCodeResult;
        
        public SearchByZipCodeResponse() {
        }
        
        public SearchByZipCodeResponse(TraderaWebService.SearchService.SearchResult SearchByZipCodeResult) {
            this.SearchByZipCodeResult = SearchByZipCodeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SearchServiceSoapChannel : TraderaWebService.SearchService.SearchServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public TraderaWebService.SearchService.SearchResult Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((TraderaWebService.SearchService.SearchResult)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearchAdvancedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SearchAdvancedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public TraderaWebService.SearchService.SearchResult Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((TraderaWebService.SearchService.SearchResult)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearchCategoryCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SearchCategoryCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public TraderaWebService.SearchService.CategoryCountResult Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((TraderaWebService.SearchService.CategoryCountResult)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearchByFixedCriteriaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SearchByFixedCriteriaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public TraderaWebService.SearchService.SearchResult Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((TraderaWebService.SearchService.SearchResult)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearchByZipCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SearchByZipCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public TraderaWebService.SearchService.SearchResult Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((TraderaWebService.SearchService.SearchResult)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearchServiceSoapClient : System.ServiceModel.ClientBase<TraderaWebService.SearchService.SearchServiceSoap>, TraderaWebService.SearchService.SearchServiceSoap {
        
        private BeginOperationDelegate onBeginSearchDelegate;
        
        private EndOperationDelegate onEndSearchDelegate;
        
        private System.Threading.SendOrPostCallback onSearchCompletedDelegate;
        
        private BeginOperationDelegate onBeginSearchAdvancedDelegate;
        
        private EndOperationDelegate onEndSearchAdvancedDelegate;
        
        private System.Threading.SendOrPostCallback onSearchAdvancedCompletedDelegate;
        
        private BeginOperationDelegate onBeginSearchCategoryCountDelegate;
        
        private EndOperationDelegate onEndSearchCategoryCountDelegate;
        
        private System.Threading.SendOrPostCallback onSearchCategoryCountCompletedDelegate;
        
        private BeginOperationDelegate onBeginSearchByFixedCriteriaDelegate;
        
        private EndOperationDelegate onEndSearchByFixedCriteriaDelegate;
        
        private System.Threading.SendOrPostCallback onSearchByFixedCriteriaCompletedDelegate;
        
        private BeginOperationDelegate onBeginSearchByZipCodeDelegate;
        
        private EndOperationDelegate onEndSearchByZipCodeDelegate;
        
        private System.Threading.SendOrPostCallback onSearchByZipCodeCompletedDelegate;
        
        public SearchServiceSoapClient() {
        }
        
        public SearchServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SearchServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<SearchCompletedEventArgs> SearchCompleted;
        
        public event System.EventHandler<SearchAdvancedCompletedEventArgs> SearchAdvancedCompleted;
        
        public event System.EventHandler<SearchCategoryCountCompletedEventArgs> SearchCategoryCountCompleted;
        
        public event System.EventHandler<SearchByFixedCriteriaCompletedEventArgs> SearchByFixedCriteriaCompleted;
        
        public event System.EventHandler<SearchByZipCodeCompletedEventArgs> SearchByZipCodeCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TraderaWebService.SearchService.SearchResponse TraderaWebService.SearchService.SearchServiceSoap.Search(TraderaWebService.SearchService.SearchRequest request) {
            return base.Channel.Search(request);
        }
        
        public TraderaWebService.SearchService.SearchResult Search(TraderaWebService.SearchService.AuthenticationHeader AuthenticationHeader, TraderaWebService.SearchService.ConfigurationHeader ConfigurationHeader, string query, int categoryId, int pageNumber, string orderBy) {
            TraderaWebService.SearchService.SearchRequest inValue = new TraderaWebService.SearchService.SearchRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.ConfigurationHeader = ConfigurationHeader;
            inValue.query = query;
            inValue.categoryId = categoryId;
            inValue.pageNumber = pageNumber;
            inValue.orderBy = orderBy;
            TraderaWebService.SearchService.SearchResponse retVal = ((TraderaWebService.SearchService.SearchServiceSoap)(this)).Search(inValue);
            return retVal.SearchResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TraderaWebService.SearchService.SearchServiceSoap.BeginSearch(TraderaWebService.SearchService.SearchRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSearch(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSearch(TraderaWebService.SearchService.AuthenticationHeader AuthenticationHeader, TraderaWebService.SearchService.ConfigurationHeader ConfigurationHeader, string query, int categoryId, int pageNumber, string orderBy, System.AsyncCallback callback, object asyncState) {
            TraderaWebService.SearchService.SearchRequest inValue = new TraderaWebService.SearchService.SearchRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.ConfigurationHeader = ConfigurationHeader;
            inValue.query = query;
            inValue.categoryId = categoryId;
            inValue.pageNumber = pageNumber;
            inValue.orderBy = orderBy;
            return ((TraderaWebService.SearchService.SearchServiceSoap)(this)).BeginSearch(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TraderaWebService.SearchService.SearchResponse TraderaWebService.SearchService.SearchServiceSoap.EndSearch(System.IAsyncResult result) {
            return base.Channel.EndSearch(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public TraderaWebService.SearchService.SearchResult EndSearch(System.IAsyncResult result) {
            TraderaWebService.SearchService.SearchResponse retVal = ((TraderaWebService.SearchService.SearchServiceSoap)(this)).EndSearch(result);
            return retVal.SearchResult;
        }
        
        private System.IAsyncResult OnBeginSearch(object[] inValues, System.AsyncCallback callback, object asyncState) {
            TraderaWebService.SearchService.AuthenticationHeader AuthenticationHeader = ((TraderaWebService.SearchService.AuthenticationHeader)(inValues[0]));
            TraderaWebService.SearchService.ConfigurationHeader ConfigurationHeader = ((TraderaWebService.SearchService.ConfigurationHeader)(inValues[1]));
            string query = ((string)(inValues[2]));
            int categoryId = ((int)(inValues[3]));
            int pageNumber = ((int)(inValues[4]));
            string orderBy = ((string)(inValues[5]));
            return this.BeginSearch(AuthenticationHeader, ConfigurationHeader, query, categoryId, pageNumber, orderBy, callback, asyncState);
        }
        
        private object[] OnEndSearch(System.IAsyncResult result) {
            TraderaWebService.SearchService.SearchResult retVal = this.EndSearch(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSearchCompleted(object state) {
            if ((this.SearchCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SearchCompleted(this, new SearchCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SearchAsync(TraderaWebService.SearchService.AuthenticationHeader AuthenticationHeader, TraderaWebService.SearchService.ConfigurationHeader ConfigurationHeader, string query, int categoryId, int pageNumber, string orderBy) {
            this.SearchAsync(AuthenticationHeader, ConfigurationHeader, query, categoryId, pageNumber, orderBy, null);
        }
        
        public void SearchAsync(TraderaWebService.SearchService.AuthenticationHeader AuthenticationHeader, TraderaWebService.SearchService.ConfigurationHeader ConfigurationHeader, string query, int categoryId, int pageNumber, string orderBy, object userState) {
            if ((this.onBeginSearchDelegate == null)) {
                this.onBeginSearchDelegate = new BeginOperationDelegate(this.OnBeginSearch);
            }
            if ((this.onEndSearchDelegate == null)) {
                this.onEndSearchDelegate = new EndOperationDelegate(this.OnEndSearch);
            }
            if ((this.onSearchCompletedDelegate == null)) {
                this.onSearchCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSearchCompleted);
            }
            base.InvokeAsync(this.onBeginSearchDelegate, new object[] {
                        AuthenticationHeader,
                        ConfigurationHeader,
                        query,
                        categoryId,
                        pageNumber,
                        orderBy}, this.onEndSearchDelegate, this.onSearchCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TraderaWebService.SearchService.SearchAdvancedResponse TraderaWebService.SearchService.SearchServiceSoap.SearchAdvanced(TraderaWebService.SearchService.SearchAdvancedRequest1 request) {
            return base.Channel.SearchAdvanced(request);
        }
        
        public TraderaWebService.SearchService.SearchResult SearchAdvanced(TraderaWebService.SearchService.AuthenticationHeader AuthenticationHeader, TraderaWebService.SearchService.ConfigurationHeader ConfigurationHeader, TraderaWebService.SearchService.SearchAdvancedRequest request) {
            TraderaWebService.SearchService.SearchAdvancedRequest1 inValue = new TraderaWebService.SearchService.SearchAdvancedRequest1();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.ConfigurationHeader = ConfigurationHeader;
            inValue.request = request;
            TraderaWebService.SearchService.SearchAdvancedResponse retVal = ((TraderaWebService.SearchService.SearchServiceSoap)(this)).SearchAdvanced(inValue);
            return retVal.SearchAdvancedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TraderaWebService.SearchService.SearchServiceSoap.BeginSearchAdvanced(TraderaWebService.SearchService.SearchAdvancedRequest1 request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSearchAdvanced(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSearchAdvanced(TraderaWebService.SearchService.AuthenticationHeader AuthenticationHeader, TraderaWebService.SearchService.ConfigurationHeader ConfigurationHeader, TraderaWebService.SearchService.SearchAdvancedRequest request, System.AsyncCallback callback, object asyncState) {
            TraderaWebService.SearchService.SearchAdvancedRequest1 inValue = new TraderaWebService.SearchService.SearchAdvancedRequest1();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.ConfigurationHeader = ConfigurationHeader;
            inValue.request = request;
            return ((TraderaWebService.SearchService.SearchServiceSoap)(this)).BeginSearchAdvanced(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TraderaWebService.SearchService.SearchAdvancedResponse TraderaWebService.SearchService.SearchServiceSoap.EndSearchAdvanced(System.IAsyncResult result) {
            return base.Channel.EndSearchAdvanced(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public TraderaWebService.SearchService.SearchResult EndSearchAdvanced(System.IAsyncResult result) {
            TraderaWebService.SearchService.SearchAdvancedResponse retVal = ((TraderaWebService.SearchService.SearchServiceSoap)(this)).EndSearchAdvanced(result);
            return retVal.SearchAdvancedResult;
        }
        
        private System.IAsyncResult OnBeginSearchAdvanced(object[] inValues, System.AsyncCallback callback, object asyncState) {
            TraderaWebService.SearchService.AuthenticationHeader AuthenticationHeader = ((TraderaWebService.SearchService.AuthenticationHeader)(inValues[0]));
            TraderaWebService.SearchService.ConfigurationHeader ConfigurationHeader = ((TraderaWebService.SearchService.ConfigurationHeader)(inValues[1]));
            TraderaWebService.SearchService.SearchAdvancedRequest request = ((TraderaWebService.SearchService.SearchAdvancedRequest)(inValues[2]));
            return this.BeginSearchAdvanced(AuthenticationHeader, ConfigurationHeader, request, callback, asyncState);
        }
        
        private object[] OnEndSearchAdvanced(System.IAsyncResult result) {
            TraderaWebService.SearchService.SearchResult retVal = this.EndSearchAdvanced(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSearchAdvancedCompleted(object state) {
            if ((this.SearchAdvancedCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SearchAdvancedCompleted(this, new SearchAdvancedCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SearchAdvancedAsync(TraderaWebService.SearchService.AuthenticationHeader AuthenticationHeader, TraderaWebService.SearchService.ConfigurationHeader ConfigurationHeader, TraderaWebService.SearchService.SearchAdvancedRequest request) {
            this.SearchAdvancedAsync(AuthenticationHeader, ConfigurationHeader, request, null);
        }
        
        public void SearchAdvancedAsync(TraderaWebService.SearchService.AuthenticationHeader AuthenticationHeader, TraderaWebService.SearchService.ConfigurationHeader ConfigurationHeader, TraderaWebService.SearchService.SearchAdvancedRequest request, object userState) {
            if ((this.onBeginSearchAdvancedDelegate == null)) {
                this.onBeginSearchAdvancedDelegate = new BeginOperationDelegate(this.OnBeginSearchAdvanced);
            }
            if ((this.onEndSearchAdvancedDelegate == null)) {
                this.onEndSearchAdvancedDelegate = new EndOperationDelegate(this.OnEndSearchAdvanced);
            }
            if ((this.onSearchAdvancedCompletedDelegate == null)) {
                this.onSearchAdvancedCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSearchAdvancedCompleted);
            }
            base.InvokeAsync(this.onBeginSearchAdvancedDelegate, new object[] {
                        AuthenticationHeader,
                        ConfigurationHeader,
                        request}, this.onEndSearchAdvancedDelegate, this.onSearchAdvancedCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TraderaWebService.SearchService.SearchCategoryCountResponse TraderaWebService.SearchService.SearchServiceSoap.SearchCategoryCount(TraderaWebService.SearchService.SearchCategoryCountRequest request) {
            return base.Channel.SearchCategoryCount(request);
        }
        
        public TraderaWebService.SearchService.CategoryCountResult SearchCategoryCount(TraderaWebService.SearchService.AuthenticationHeader AuthenticationHeader, TraderaWebService.SearchService.ConfigurationHeader ConfigurationHeader, TraderaWebService.SearchService.CategoryCountRequest request) {
            TraderaWebService.SearchService.SearchCategoryCountRequest inValue = new TraderaWebService.SearchService.SearchCategoryCountRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.ConfigurationHeader = ConfigurationHeader;
            inValue.request = request;
            TraderaWebService.SearchService.SearchCategoryCountResponse retVal = ((TraderaWebService.SearchService.SearchServiceSoap)(this)).SearchCategoryCount(inValue);
            return retVal.SearchCategoryCountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TraderaWebService.SearchService.SearchServiceSoap.BeginSearchCategoryCount(TraderaWebService.SearchService.SearchCategoryCountRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSearchCategoryCount(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSearchCategoryCount(TraderaWebService.SearchService.AuthenticationHeader AuthenticationHeader, TraderaWebService.SearchService.ConfigurationHeader ConfigurationHeader, TraderaWebService.SearchService.CategoryCountRequest request, System.AsyncCallback callback, object asyncState) {
            TraderaWebService.SearchService.SearchCategoryCountRequest inValue = new TraderaWebService.SearchService.SearchCategoryCountRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.ConfigurationHeader = ConfigurationHeader;
            inValue.request = request;
            return ((TraderaWebService.SearchService.SearchServiceSoap)(this)).BeginSearchCategoryCount(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TraderaWebService.SearchService.SearchCategoryCountResponse TraderaWebService.SearchService.SearchServiceSoap.EndSearchCategoryCount(System.IAsyncResult result) {
            return base.Channel.EndSearchCategoryCount(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public TraderaWebService.SearchService.CategoryCountResult EndSearchCategoryCount(System.IAsyncResult result) {
            TraderaWebService.SearchService.SearchCategoryCountResponse retVal = ((TraderaWebService.SearchService.SearchServiceSoap)(this)).EndSearchCategoryCount(result);
            return retVal.SearchCategoryCountResult;
        }
        
        private System.IAsyncResult OnBeginSearchCategoryCount(object[] inValues, System.AsyncCallback callback, object asyncState) {
            TraderaWebService.SearchService.AuthenticationHeader AuthenticationHeader = ((TraderaWebService.SearchService.AuthenticationHeader)(inValues[0]));
            TraderaWebService.SearchService.ConfigurationHeader ConfigurationHeader = ((TraderaWebService.SearchService.ConfigurationHeader)(inValues[1]));
            TraderaWebService.SearchService.CategoryCountRequest request = ((TraderaWebService.SearchService.CategoryCountRequest)(inValues[2]));
            return this.BeginSearchCategoryCount(AuthenticationHeader, ConfigurationHeader, request, callback, asyncState);
        }
        
        private object[] OnEndSearchCategoryCount(System.IAsyncResult result) {
            TraderaWebService.SearchService.CategoryCountResult retVal = this.EndSearchCategoryCount(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSearchCategoryCountCompleted(object state) {
            if ((this.SearchCategoryCountCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SearchCategoryCountCompleted(this, new SearchCategoryCountCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SearchCategoryCountAsync(TraderaWebService.SearchService.AuthenticationHeader AuthenticationHeader, TraderaWebService.SearchService.ConfigurationHeader ConfigurationHeader, TraderaWebService.SearchService.CategoryCountRequest request) {
            this.SearchCategoryCountAsync(AuthenticationHeader, ConfigurationHeader, request, null);
        }
        
        public void SearchCategoryCountAsync(TraderaWebService.SearchService.AuthenticationHeader AuthenticationHeader, TraderaWebService.SearchService.ConfigurationHeader ConfigurationHeader, TraderaWebService.SearchService.CategoryCountRequest request, object userState) {
            if ((this.onBeginSearchCategoryCountDelegate == null)) {
                this.onBeginSearchCategoryCountDelegate = new BeginOperationDelegate(this.OnBeginSearchCategoryCount);
            }
            if ((this.onEndSearchCategoryCountDelegate == null)) {
                this.onEndSearchCategoryCountDelegate = new EndOperationDelegate(this.OnEndSearchCategoryCount);
            }
            if ((this.onSearchCategoryCountCompletedDelegate == null)) {
                this.onSearchCategoryCountCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSearchCategoryCountCompleted);
            }
            base.InvokeAsync(this.onBeginSearchCategoryCountDelegate, new object[] {
                        AuthenticationHeader,
                        ConfigurationHeader,
                        request}, this.onEndSearchCategoryCountDelegate, this.onSearchCategoryCountCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TraderaWebService.SearchService.SearchByFixedCriteriaResponse TraderaWebService.SearchService.SearchServiceSoap.SearchByFixedCriteria(TraderaWebService.SearchService.SearchByFixedCriteriaRequest1 request) {
            return base.Channel.SearchByFixedCriteria(request);
        }
        
        public TraderaWebService.SearchService.SearchResult SearchByFixedCriteria(TraderaWebService.SearchService.AuthenticationHeader AuthenticationHeader, TraderaWebService.SearchService.ConfigurationHeader ConfigurationHeader, TraderaWebService.SearchService.SearchByFixedCriteriaRequest request) {
            TraderaWebService.SearchService.SearchByFixedCriteriaRequest1 inValue = new TraderaWebService.SearchService.SearchByFixedCriteriaRequest1();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.ConfigurationHeader = ConfigurationHeader;
            inValue.request = request;
            TraderaWebService.SearchService.SearchByFixedCriteriaResponse retVal = ((TraderaWebService.SearchService.SearchServiceSoap)(this)).SearchByFixedCriteria(inValue);
            return retVal.SearchByFixedCriteriaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TraderaWebService.SearchService.SearchServiceSoap.BeginSearchByFixedCriteria(TraderaWebService.SearchService.SearchByFixedCriteriaRequest1 request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSearchByFixedCriteria(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSearchByFixedCriteria(TraderaWebService.SearchService.AuthenticationHeader AuthenticationHeader, TraderaWebService.SearchService.ConfigurationHeader ConfigurationHeader, TraderaWebService.SearchService.SearchByFixedCriteriaRequest request, System.AsyncCallback callback, object asyncState) {
            TraderaWebService.SearchService.SearchByFixedCriteriaRequest1 inValue = new TraderaWebService.SearchService.SearchByFixedCriteriaRequest1();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.ConfigurationHeader = ConfigurationHeader;
            inValue.request = request;
            return ((TraderaWebService.SearchService.SearchServiceSoap)(this)).BeginSearchByFixedCriteria(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TraderaWebService.SearchService.SearchByFixedCriteriaResponse TraderaWebService.SearchService.SearchServiceSoap.EndSearchByFixedCriteria(System.IAsyncResult result) {
            return base.Channel.EndSearchByFixedCriteria(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public TraderaWebService.SearchService.SearchResult EndSearchByFixedCriteria(System.IAsyncResult result) {
            TraderaWebService.SearchService.SearchByFixedCriteriaResponse retVal = ((TraderaWebService.SearchService.SearchServiceSoap)(this)).EndSearchByFixedCriteria(result);
            return retVal.SearchByFixedCriteriaResult;
        }
        
        private System.IAsyncResult OnBeginSearchByFixedCriteria(object[] inValues, System.AsyncCallback callback, object asyncState) {
            TraderaWebService.SearchService.AuthenticationHeader AuthenticationHeader = ((TraderaWebService.SearchService.AuthenticationHeader)(inValues[0]));
            TraderaWebService.SearchService.ConfigurationHeader ConfigurationHeader = ((TraderaWebService.SearchService.ConfigurationHeader)(inValues[1]));
            TraderaWebService.SearchService.SearchByFixedCriteriaRequest request = ((TraderaWebService.SearchService.SearchByFixedCriteriaRequest)(inValues[2]));
            return this.BeginSearchByFixedCriteria(AuthenticationHeader, ConfigurationHeader, request, callback, asyncState);
        }
        
        private object[] OnEndSearchByFixedCriteria(System.IAsyncResult result) {
            TraderaWebService.SearchService.SearchResult retVal = this.EndSearchByFixedCriteria(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSearchByFixedCriteriaCompleted(object state) {
            if ((this.SearchByFixedCriteriaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SearchByFixedCriteriaCompleted(this, new SearchByFixedCriteriaCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SearchByFixedCriteriaAsync(TraderaWebService.SearchService.AuthenticationHeader AuthenticationHeader, TraderaWebService.SearchService.ConfigurationHeader ConfigurationHeader, TraderaWebService.SearchService.SearchByFixedCriteriaRequest request) {
            this.SearchByFixedCriteriaAsync(AuthenticationHeader, ConfigurationHeader, request, null);
        }
        
        public void SearchByFixedCriteriaAsync(TraderaWebService.SearchService.AuthenticationHeader AuthenticationHeader, TraderaWebService.SearchService.ConfigurationHeader ConfigurationHeader, TraderaWebService.SearchService.SearchByFixedCriteriaRequest request, object userState) {
            if ((this.onBeginSearchByFixedCriteriaDelegate == null)) {
                this.onBeginSearchByFixedCriteriaDelegate = new BeginOperationDelegate(this.OnBeginSearchByFixedCriteria);
            }
            if ((this.onEndSearchByFixedCriteriaDelegate == null)) {
                this.onEndSearchByFixedCriteriaDelegate = new EndOperationDelegate(this.OnEndSearchByFixedCriteria);
            }
            if ((this.onSearchByFixedCriteriaCompletedDelegate == null)) {
                this.onSearchByFixedCriteriaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSearchByFixedCriteriaCompleted);
            }
            base.InvokeAsync(this.onBeginSearchByFixedCriteriaDelegate, new object[] {
                        AuthenticationHeader,
                        ConfigurationHeader,
                        request}, this.onEndSearchByFixedCriteriaDelegate, this.onSearchByFixedCriteriaCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TraderaWebService.SearchService.SearchByZipCodeResponse TraderaWebService.SearchService.SearchServiceSoap.SearchByZipCode(TraderaWebService.SearchService.SearchByZipCodeRequest1 request) {
            return base.Channel.SearchByZipCode(request);
        }
        
        public TraderaWebService.SearchService.SearchResult SearchByZipCode(TraderaWebService.SearchService.AuthenticationHeader AuthenticationHeader, TraderaWebService.SearchService.ConfigurationHeader ConfigurationHeader, TraderaWebService.SearchService.SearchByZipCodeRequest request) {
            TraderaWebService.SearchService.SearchByZipCodeRequest1 inValue = new TraderaWebService.SearchService.SearchByZipCodeRequest1();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.ConfigurationHeader = ConfigurationHeader;
            inValue.request = request;
            TraderaWebService.SearchService.SearchByZipCodeResponse retVal = ((TraderaWebService.SearchService.SearchServiceSoap)(this)).SearchByZipCode(inValue);
            return retVal.SearchByZipCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TraderaWebService.SearchService.SearchServiceSoap.BeginSearchByZipCode(TraderaWebService.SearchService.SearchByZipCodeRequest1 request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSearchByZipCode(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSearchByZipCode(TraderaWebService.SearchService.AuthenticationHeader AuthenticationHeader, TraderaWebService.SearchService.ConfigurationHeader ConfigurationHeader, TraderaWebService.SearchService.SearchByZipCodeRequest request, System.AsyncCallback callback, object asyncState) {
            TraderaWebService.SearchService.SearchByZipCodeRequest1 inValue = new TraderaWebService.SearchService.SearchByZipCodeRequest1();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.ConfigurationHeader = ConfigurationHeader;
            inValue.request = request;
            return ((TraderaWebService.SearchService.SearchServiceSoap)(this)).BeginSearchByZipCode(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TraderaWebService.SearchService.SearchByZipCodeResponse TraderaWebService.SearchService.SearchServiceSoap.EndSearchByZipCode(System.IAsyncResult result) {
            return base.Channel.EndSearchByZipCode(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public TraderaWebService.SearchService.SearchResult EndSearchByZipCode(System.IAsyncResult result) {
            TraderaWebService.SearchService.SearchByZipCodeResponse retVal = ((TraderaWebService.SearchService.SearchServiceSoap)(this)).EndSearchByZipCode(result);
            return retVal.SearchByZipCodeResult;
        }
        
        private System.IAsyncResult OnBeginSearchByZipCode(object[] inValues, System.AsyncCallback callback, object asyncState) {
            TraderaWebService.SearchService.AuthenticationHeader AuthenticationHeader = ((TraderaWebService.SearchService.AuthenticationHeader)(inValues[0]));
            TraderaWebService.SearchService.ConfigurationHeader ConfigurationHeader = ((TraderaWebService.SearchService.ConfigurationHeader)(inValues[1]));
            TraderaWebService.SearchService.SearchByZipCodeRequest request = ((TraderaWebService.SearchService.SearchByZipCodeRequest)(inValues[2]));
            return this.BeginSearchByZipCode(AuthenticationHeader, ConfigurationHeader, request, callback, asyncState);
        }
        
        private object[] OnEndSearchByZipCode(System.IAsyncResult result) {
            TraderaWebService.SearchService.SearchResult retVal = this.EndSearchByZipCode(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSearchByZipCodeCompleted(object state) {
            if ((this.SearchByZipCodeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SearchByZipCodeCompleted(this, new SearchByZipCodeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SearchByZipCodeAsync(TraderaWebService.SearchService.AuthenticationHeader AuthenticationHeader, TraderaWebService.SearchService.ConfigurationHeader ConfigurationHeader, TraderaWebService.SearchService.SearchByZipCodeRequest request) {
            this.SearchByZipCodeAsync(AuthenticationHeader, ConfigurationHeader, request, null);
        }
        
        public void SearchByZipCodeAsync(TraderaWebService.SearchService.AuthenticationHeader AuthenticationHeader, TraderaWebService.SearchService.ConfigurationHeader ConfigurationHeader, TraderaWebService.SearchService.SearchByZipCodeRequest request, object userState) {
            if ((this.onBeginSearchByZipCodeDelegate == null)) {
                this.onBeginSearchByZipCodeDelegate = new BeginOperationDelegate(this.OnBeginSearchByZipCode);
            }
            if ((this.onEndSearchByZipCodeDelegate == null)) {
                this.onEndSearchByZipCodeDelegate = new EndOperationDelegate(this.OnEndSearchByZipCode);
            }
            if ((this.onSearchByZipCodeCompletedDelegate == null)) {
                this.onSearchByZipCodeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSearchByZipCodeCompleted);
            }
            base.InvokeAsync(this.onBeginSearchByZipCodeDelegate, new object[] {
                        AuthenticationHeader,
                        ConfigurationHeader,
                        request}, this.onEndSearchByZipCodeDelegate, this.onSearchByZipCodeCompletedDelegate, userState);
        }
    }
}
